 apiVersion: v1
 kind: Service
 metadata:
   name: nginx-svc
   namespace: default
   annotations:
     metallb.universe.tf/loadBalancerIPs: 37.230.116.88
 spec:
   type: LoadBalancer
   selector:
     app: nginx
   ports:
   - protocol: TCP
     port: 80