apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: default
data:
  default.conf: |
    server {
        server_name vitaliypryhodko.fvds.ru;
        listen 80;
        location / {
#            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://art-service:80;
        }
    }
