name: RPROXY-WF

on: push

jobs:

  deploy:
    name: Rproxy-Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: https://194.87.147.125:6443/
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kubernetes/nginx-deploy.yaml
            kubernetes/nginx-cm.yaml
            kubernetes/nginx-svc.yaml